import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import 'leaflet/dist/leaflet.css'
import LucideProvider from '@/providers/lucide-provider'
import Sidemenu from '@/components/navigation/sidemenu'
import Header from '@/components/header/header'
import '@ant-design/v5-patch-for-react-19'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Markdown Map Marker',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Sidemenu />
        {children}
        <LucideProvider />
      </body>
    </html>
  )
}
